addons:
  postgresql: "9.4"

services:
  - postgresql
  - mysql

language: scala
scala:
   - 2.11.7
branches:
  only:
    - master
notifications:
  email:
    recipients:
      - paweld2@gmail.com
jdk:
  - oraclejdk8

before_script:

  - psql -c "CREATE USER eventStoreTestUser WITH PASSWORD 'eventStoreTestPassword';" -U postgres
  - psql -c 'ALTER USER eventStoreTestUser CREATEDB;' -U postgres
  - psql -c 'DROP DATABASE IF EXISTS eventStoreTestPostgres;' -U postgres
  - psql -c 'CREATE DATABASE eventStoreTestPostgres;' -U postgres
  - psql -c 'GRANT ALL PRIVILEGES ON DATABASE eventStoreTestPostgres TO eventStoreTestUser;' -U postgres
  - mysql -e "create database IF NOT EXISTS eventStoreTestMySql;" -uroot


script: sbt ++$TRAVIS_SCALA_VERSION clean coverage test